### Create a new user
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test444@test.com",
    "password": "123test123"
}

### Signin 
POST  http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test444@test.com",
    "password": "123test123"
}

### List all users by email

GET http://localhost:3000/auth?email=test@test.com

### Get a particular user

GET http://localhost:3000/auth/2


### Delete a particular user

DELETE  http://localhost:3000/auth/3


### Patch a particular user

PATCH   http://localhost:3000/auth/2
Content-Type: application/json

{
    "email": "test2@test2.com"
}
